web_service/app/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
    SpectacularRedocView,
)

from rest_framework_nested import routers

from app.views import (
    index,
    OCPNViewSet,
    FilteredOCELViewSet,
    EnhancementViewSet,
)
from web_service import settings

app_name = "app"

router = routers.SimpleRouter()
router.register(r"ocpn", OCPNViewSet, basename="ocpn")


filtered_ocel_router = routers.NestedSimpleRouter(router, r"ocpn", lookup="ocpn")
filtered_ocel_router.register(
    r"filtered_ocels", FilteredOCELViewSet, basename="filtered_ocel"
)


enhancement_router = routers.NestedSimpleRouter(router, r"ocpn", lookup="ocpn")
enhancement_router.register(r"enhancements", EnhancementViewSet, basename="enhancement")

urlpatterns = [
    path("", index, name="index"),
    path("api/", include(router.urls)),
    path("api/", include(filtered_ocel_router.urls)),
    path("api/", include(enhancement_router.urls)),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="app:schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="app:schema"),
        name="redoc",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_service/web_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("app.urls", namespace="app")),
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("docs/", include('docs.urls'))
]

web_service/app/templates/base.html
{% load static %}
{% load compress %}
{% load sekizai_tags %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="application-name" content="Chestnut {{ PRODUCT_NAME_SHORT }}">
    <title>{{ PRODUCT_NAME_SHORT }} - {% block title %}{% endblock %}</title>
    {# Scripts #}
    <!-- Import Bootstrap 5 bundle -->
    <script type="text/javascript" src="{% static 'js/vendor/bootstrap/bootstrap.bundle.min.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'js/vendor/jquery/jquery-3.6.1.min.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'js/vendor/datatables/datatables.min.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'js/vendor/datatables/select.dataTables.min.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'js/vendor/cytoscape/cytoscape.min.js' %}" defer></script>
{#    <script type="text/javascript" src="{% static 'js/vendor/viz/viz.js' %}" defer></script>#}
{#    <script type="text/javascript" src="{% static 'js/vendor/viz/full.render.js' %}" defer></script>#}
    <script type="text/javascript" src="{% static 'js/vendor/klay/klay.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'js/vendor/klay/cytoscape-klay.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'js/vendor/elk/elk.bundled.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'js/vendor/elk/cytoscape-elk.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'js/vendor/d3/d3.v4.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'js/constants.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'js/utility.js' %}" defer></script>

    {% block scripts %}
    {% endblock %}
    {% render_block "js" %}

    {# Favicon #}
{#    <link rel="shortcut icon" href="{% static 'images/favicons/favicon.ico' %}">#}

    {# CSS #}
    {% compress css %}
    <link type="text/x-scss" href="{% static 'scss/style.scss' %}" rel="stylesheet">
    {% endcompress %}


    {% block css %}

    {% endblock %}
    {% render_block 'css' %}
    {# Favicons #}

</head>
<body>
<div id="toastMessageContainer" class="position-fixed bottom-0 end-0 mb-2 me-2 z-2000">
    {% include 'toast_message.html' %}
</div>
<div id="current_user_info">
    <input disabled type="hidden" id="user_name" value="{{ name }}">
</div>
<input disabled id="static_dir" type="hidden" value="{% static ''%}">
{% include 'topbar.html'%}
<div class="wrapper position-relative">

{#    {% include 'sidebar.html' %}#}

    <!-- Page Content  -->
    <div id="content">

        <div class="content-wrapper">
            {% block content %}
            {% endblock content %}
        </div>

{#        {% include 'footer.html' %}#}
    </div>

</div>
{% block modal_templates %} {% endblock %}
{% render_block "modal_templates" %}

</body>
</html>

web_service/app/templates/enhancement.html
{% load static %}
{% load sekizai_tags %}
{% csrf_token %}
<div class="row mt-3 d-none" id="enhancementContainer">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <div id="enhancementWrapper-left">
                    <div id="enhancementForm-left">
                        <div class="row justify-content-center">
                            <div class="col-auto">
                                <button type="button" class="btn btn-outline-primary" id="enhancementSelectionModeButton-left">
                                    <i class="fas fa-plus"></i> Choose Activity
                                </button>
                            </div>
                        </div>
                    </div>
                    <div id="enhancementContainer-left">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-body">
                <div id="enhancementWrapper-right">
                    <div id="enhancementForm-right">
                        <div class="row justify-content-center">
                            <div class="col-auto">
                                <button type="button" class="btn btn-outline-primary" id="enhancementSelectionModeButton-right">
                                    <i class="fas fa-plus"></i> Choose Activity
                                </button>
                            </div>
                        </div>
                    </div>
                    <div id="enhancementContainer-right">
                    </div>
                </div>
            </div>
        </div>
    </div>
{#    <div class="col">#}
{#        <div id="enhancementWrapper">#}
{#            <div id="enhancementForm">#}
{#            </div>#}
{#            <div id="enhancementContainer">#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
</div>
{% addtoblock "js" %}
<script type="text/javascript" src="{% static 'js/enhancement.js' %}" defer></script>
{% endaddtoblock %}

web_service/app/templates/filter.html
{% load static %}
{% load sekizai_tags %}


<div id="filterWrapper" class="col border-start d-none">
    <div class="row">
        <div class="col">
            <h5>Filter Settings</h5>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="row mb-3 align-content-center">
                <label for="filterFitnessThreshold" class="col-3 col-form-label">Fitness Threshold: <i type="button" data-bs-toggle="tooltip" title="The fitness filter allows us to replay the object-centric event log on the discovered object-centric Petri net and filter out objects that do not meet a specified fitness requirement. For this, we replay each object on a flattened version of its object type’s Petri net and calculate the corresponding trace fitness. If this is below the passed threshold the object is filtered out. In case all objects related to an event are removed, the event will be removed as well" class="fa fa-info-circle"></i></label>
                <div class="col-1">
                    <input type="text" class="form-control" id="filterFitnessThreshold">
                </div>
                <div class="col-auto col-form-label">
                    <label class="form-check-label" for="replayTypeSelect">
                        Replay Type:
                    </label>
                </div>
                <div class="col-auto">
                    <select class="form-select" aria-label="Default select example" id="replayTypeSelect">
                        <option selected value="token">Token-based</option>
                        <option value="alignment">Alignment-based </option>
                    </select>
{#                    <div class="form-check">#}
{#                        <input class="form-check-input" type="checkbox" value="" id="mustUseAllCheckbox">#}
{#                        <label class="form-check-label" for="mustUseAllCheckbox">#}
{#                            Must use all Activities#}
{#                            <i type="button" data-bs-toggle="tooltip" title="If not selected, we filter out objects that do not contain any of the desired activities in their lifetime. If this option is selected, we ensure that all of the desired activities must occur for each object that is kept" class="fa fa-info-circle"></i>#}
{#                        </label>#}
{#                    </div>#}
                </div>
            </div>
            <div class="row mb-3 align-items-center">
                <label for="filterActivities" class="col-3 col-form-label">Select activities of interest: <i type="button" data-bs-toggle="tooltip" title="The activity filter allows us to filter out objects that are not involved in the execution of events with the selected activities" class="fa fa-info-circle"></i></label>
                <div class="input-group col">
                    <input type="text" class="form-control" id="filterActivities" readonly>
                    <button class="btn btn-outline-primary" type="button" id="selectionModeButton">Select Transitions</button>
                </div>
                <div class="col-auto">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="mustUseAllCheckbox">
                        <label class="form-check-label" for="mustUseAllCheckbox">
                            Must use all Activities
                            <i type="button" data-bs-toggle="tooltip" title="If not selected, we filter out objects that do not contain any of the desired activities in their lifetime. If this option is selected, we ensure that all of the desired activities must occur for each object that is kept" class="fa fa-info-circle"></i>
                        </label>
                    </div>
                </div>
            </div>
            <div class="row mb-3">
                <label class="col-3 col-form-label">Select time span: <i type="button" data-bs-toggle="tooltip" title="Events outside of the selected time-frame are no longer considered" class="fa fa-info-circle"></i></label>
                <div class="col-auto">
                    <div class="row">
                        <label for="timeFrom" class="col-form-label col-auto me-3">from:</label>
                        <div class="col-auto">
                            <input type="datetime-local" class="form-control me-3" id="timeFrom">
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    <div class="row">
                        <label for="timeTo" class="col-form-label col-auto me-3">to:</label>
                        <div class="col-auto">
                            <input type="datetime-local" class="form-control col-3" id="timeTo">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-end">
        <div class="col-auto">
            <button type="button" class="btn btn-primary" id="applyFilterButton">
                Apply Filter
            </button>
            <button type="button" class="btn btn-secondary ms-2 d-none" id="removeFilterButton">
                Remove Filter
            </button>
        </div>
    </div>
</div>

{% addtoblock "js" %}
    <script type="text/javascript" src="{% static 'js/filter.js' %}" defer></script>
{% endaddtoblock %}

web_service/app/templates/import.html
{% load static %}
{% load static %}
{% load sekizai_tags %}
<form enctype="multipart/form-data" method="post">
    <form enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-3">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-OCEL-name">Name</span>
                    <input type="text" id="ocel_name" class="form-control" aria-label="OCEL Name"
                           aria-describedby="inputGroup-OCEL-name" placeholder="Name">
                </div>
            </div>
            <div class="col">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-OCEL-description">Description</span>
                    <input type="text" id="ocel_desc" class="form-control" aria-label="OCEL Description"
                           aria-describedby="inputGroup-OCEL-desc" placeholder="Description">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="{{ ocel_upload_form.ocel_file.id_for_label }}" class="form-label" hidden>OCEL file:</label>
            {{ ocel_upload_form.ocel_file }}
        </div>
        <div class="row mt-3">
            <label for="DiscoveryAlgorithm" class="col-auto col-form-label">Select a discovery algorithm: </label>
            <div class="col-5">
                <select id="DiscoveryAlgorithm" class="form-select">
                    <option value="inductive miner classic"> inductive miner classic</option>
                    <option value="inductive miner infrequent"> inductive miner infrequent</option>
                    <option value="inductive miner directly follows" selected> inductive miner directly follows</option>
                    <option value="alpha miner classic"> alpha miner classic</option>
                    <option value="alpha miner plus"> alpha miner plus</option>
                    <option value="heuristic miner classic">heuristic miner classic</option>
                    <option value="heuristic miner plus plus">heuristic miner plus plus</option>
                </select>
            </div>
            <div>
                <div class="col">
                    <div id="parameters">c</div>
                </div>
            </div>
        </div>
    </form>
</form>

{% addtoblock "js" %}
<script type="text/javascript" src="{% static 'js/parameters.js' %}" defer></script>
{% endaddtoblock %}

web_service/app/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load sekizai_tags %}

{% block title %}Home{% endblock %}

{% block content %}

    <div class="card mb-3 d-none" id="ocpn_content">
{#        <div class="card-header">#}
{#            <div class="col-12">#}
{#                <h3>Welcome</h3>#}
{#            </div>#}
{#        </div>#}
        <div class="card-body">
            {% include 'load_ocel.html' %}
{#            {% include 'import.html' %}#}
            <div id="OCPNModelWrapper" class="d-none mt-3">
                {% if ocpn_png %}
                    <img src="{{ ocpn_png }}" style="width: 100%">
                {% endif %}
            </div>
               {% include 'enhancement.html' %}
        </div>
    </div>


    <div class="wrapper position-relative">
        <div class="wrapper-load position-absolute" id="load-wrapper">
            <div class="load fadeInDown">
                <div class="formContent" id="loadContent">
                    <h3 class="load-title">Data Aware Object-Centric Petri Net</h3>
                    <div id="loadAlert" class="alert alert-danger collapse" role="alert">
                        <span></span>
                    </div>
                    <form id="load-form">
{#                        {% csrf_token %}#}
                        {#                <input type="hidden" id="next" name="next" value="{{ next }}">#}
{#                        <input type="text" id="login" class="fadeIn second" name="username" placeholder="User" required>#}
{#                        <input type="password" id="password" class="fadeIn third" name="password" placeholder="Password" required>#}
{#                        <input type="submit" class="fadeIn fourth" id="load-button" value="Load OCEL">#}

                        <button type="button" class="fadeIn fourth" data-bs-toggle="modal" data-bs-target="#loadOCELModal" id="loadOCELBtn">
                            Load OCEL
                        </button>
                    </form>
                </div>
            </div>
        </div>

    </div>
{% include 'load_modal.html' %}
{% endblock %}

{% block scripts %}
    {% addtoblock "js" %}
        <script type="text/javascript" src="{% static 'js/ocpn.js' %}" defer></script>
        <script type="text/javascript" src="{% static 'js/graph.js' %}" defer></script>
    {% endaddtoblock %}
{% endblock %}

web_service/app/templates/load_modal.html
<div class="modal modal-xl fade" id="loadOCELModal" tabindex="-1" aria-labelledby="loadOCELModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loadOCELModalLabel">Load OCEL</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row" id="newOCELFile">
                    <h6 class="mb-4">Choose new OCEL File</h6>
                    {% include 'import.html' %}
                </div>
                <div class="my-4">
                    <hr>
                </div>
                <div class="row" id="selectOCELFile">
                    <div class="col">
                        <div class="row">
                            <div class="col">
                                <h6 class="mb-3">Or choose existing OCEL File</h6>
                            </div>
                        </div>
                        <div class="row">
                            {% include 'ocel_table.html' %}
                        </div>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="persist d-flex justify-content-center">
                        <hr class="flex-grow-1 me-1">
                        <button class="persist btn btn-outline-info border-0" data-bs-target="#further_settings" data-bs-toggle="collapse">Advanced Settings ▼</button>
                        <hr class="flex-grow-1 ms-1">
                    </div>
                    <div id="further_settings" class="persist collapse mb-3">
                        <div class="form-check">
                            <input id="displayImage" class="form-check-input me-2" name="displaySetting" type="radio">
                            <label class="form-check-label" for="displayImage">
                                Display as image
                            </label>
                            <button type="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Display discovered OCPN as image" class="fa fa-info-circle btn"></button>
                        </div>
                        <div class="mb form-check">
                            <input id="displayGraph" class="form-check-input me-2" name="displaySetting" type="radio" checked>
                            <label class="form-check-label" for="displayGraph">
                                Display as interactive graph
                            </label>
                            <button type="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Display discovered OCPN as interactive graph" class="fa fa-info-circle btn"></button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="OCPNDiscoveryBtn">Start</button>
            </div>
        </div>
    </div>
</div>

web_service/app/templates/load_ocel.html
{% load static %}
{% load sekizai_tags %}

<!-- Button trigger modal -->
<div class="row">
    <div class="col-4">
        <div class="row">
            <div class="col">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#loadOCELModal">
                    Load OCEL
                </button>
            </div>
        </div>
        <div class="row">
            <div class="w-75 d-none mt-3"  id="selectedOCELWrapper">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <div>
                                    <h5 id="selectedOCELTitle">Selected OCEL: <span id="selectedOCELName">Name</span></h5>
                                    <span class="fst-italic" id="selectedOCELFile">pm4py-example.jsonocel</span> </br>
                                     <span id="selectedAlgorithm"> </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row ">
            <div class="col mt-4 d-none" id="decisionRow">
                <button type="button" class="btn btn-primary" id="toggleDecisionPointsBtn">
                    Toggle Decision Points
                    <i type="button" data-bs-toggle="tooltip" title="This toggles suggestions on decision points that might be interesting to analyze. The user can, for example, closer inspect and compare the patterns present at the outgoing transitions of a suggested decision point." class="fa fa-info-circle"></i>
                </button>
            </div>
        </div>
    </div>
    {% include 'filter.html' %}
{#    <div class="col-3">#}
{#        <div class="input-group">#}
{#          <span class="input-group-text" id="basic-addon3">Current OCEL</span>#}
{#          <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3" aria-label="Amount (to the nearest dollar)">#}
{#        </div>#}
{#    </div>#}
{#    <div class="col-3">#}
{#        <div class="input-group">#}
{#            <span class="input-group-text" id="basic-addon3">Name</span>#}
{#            <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3" aria-label="Amount (to the nearest dollar)">#}
{#        </div>#}
{#    </div>#}
{#    <div class="col-3">#}
{#        <div class="input-group">#}
{#            <span class="input-group-text" id="basic-addon3">Description</span>#}
{#            <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3" aria-label="Amount (to the nearest dollar)">#}
{#        </div>#}
{#    </div>#}
</div>

<!-- Modal -->

{% addtoblock "js" %}
    <script type="text/javascript" src="{% static 'js/ocpn_table.js' %}" defer></script>
{% endaddtoblock %}

web_service/app/templates/ocel_table.html
<table id="OCPNTable" class="table w-100">
    <thead>
    <tr>
        <th class="id">ID</th>
        <th class="name">Name</th>
        <th class="description">Description</th>
        <th class="filename">Filename</th>
        <th class="discovery_algorithm">Discovery Algorithm</th>
        <th class="file">File</th>
        <th class="action"></th>
    </tr>
    </thead>
</table>

web_service/app/templates/toast_message.html
<div class="toast mb-2" role="alert" aria-live="assertive" aria-atomic="true" id="defaultLiveToast">
  <div class="toast-header">
    <strong class="me-auto toast-main-title">Bootstrap</strong>
    <small class="toast-subtitle">11 mins ago</small>
    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
  <div class="toast-body">
    Hello, world! This is a toast message.
  </div>
</div>

web_service/app/templates/topbar.html
{% load sekizai_tags %}
{% load static %}
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div id="navbar-container" class="container-fluid">
        <div class="sidebar-header ms-3">
            <span>
                <h2 class="text-light">{{ PRODUCT_NAME }}</h2>
            </span>
        </div>

        <div>
            <a href="{% url 'app:swagger-ui' %}" target="_blank" rel="noopener noreferrer" class="me-3" style="text-decoration: none; color: white; text-decoration-color:  white">API</a>
            <a target="_blank" rel="noopener noreferrer" href="docs" style="color: white" class="me-3">
                <span title="Documentation" class="font-weight-bold">
                    <i class="fas fa-question-circle"></i>
                </span>
            </a>
        </div>

    </div>
</nav>

{% addtoblock "js" %}

{% endaddtoblock %}